# Generated by Django 2.2.6 on 2019-11-20 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course_Instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.IntegerField(max_length=5, unique=True)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('contact_no', models.IntegerField(blank=True, max_length=12, null=True, unique=True)),
                ('desc', models.TextField(blank=True, null=True, verbose_name='About Me')),
                ('image', models.ImageField(default='default.jpg', upload_to='staff_pics')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
