# Generated by Django 2.2.6 on 2019-11-20 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_instructor',
            name='contact_no',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='course_instructor',
            name='user_id',
            field=models.SmallIntegerField(unique=True),
        ),
    ]
