# Generated by Django 2.2.6 on 2019-11-20 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_auto_20191121_0125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course_instructor',
            name='user_id',
        ),
        migrations.AddField(
            model_name='course_instructor',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, max_length=150, null=True, unique=True),
        ),
    ]
