# Generated by Django 2.2.6 on 2019-11-20 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_auto_20191121_0150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course_instructor',
            name='username',
        ),
        migrations.AddField(
            model_name='course_instructor',
            name='user_id',
            field=models.SmallIntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='course_instructor',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
