# Generated by Django 2.2.6 on 2019-11-22 05:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_auto_20191121_0208'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_instructor',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.AddField(
            model_name='course_instructor',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='course_instructor',
            name='user_id',
            field=models.SmallIntegerField(unique=True),
        ),
    ]
