# Generated by Django 2.2.6 on 2019-11-26 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0005_auto_20191122_1105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=150, unique=True)),
                ('about_course', models.TextField()),
                ('prerequisit', models.TextField()),
                ('course_duration', models.CharField(max_length=30)),
                ('syllabus', models.TextField(blank=True, null=True)),
                ('course_info', models.TextField(blank=True, null=True)),
                ('course_image', models.ImageField(default='default.jpg', upload_to='course_cover_pics')),
                ('course_fee', models.IntegerField()),
                ('course_requirement', models.TextField(blank=True, null=True)),
                ('course_instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.Course_Instructor')),
            ],
        ),
        migrations.CreateModel(
            name='Course_Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=50, unique=True)),
                ('topic_order', models.SmallIntegerField()),
                ('video', models.FileField(upload_to='course_videos')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_course.Course_Detail')),
            ],
        ),
    ]
