# Generated by Django 2.2.6 on 2019-11-15 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('X_passing_year', models.IntegerField(blank=True, max_length=4, null=True)),
                ('X_school', models.CharField(blank=True, max_length=50, null=True)),
                ('X_board', models.CharField(blank=True, max_length=50, null=True)),
                ('X_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('XII_passing_year', models.IntegerField(blank=True, max_length=4, null=True)),
                ('XII_school', models.CharField(blank=True, max_length=50, null=True)),
                ('XII_board', models.CharField(blank=True, max_length=50, null=True)),
                ('XII_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('UG_passing_year', models.IntegerField(blank=True, max_length=4, null=True)),
                ('UG_school', models.CharField(blank=True, max_length=50, null=True)),
                ('UG_board', models.CharField(blank=True, max_length=50, null=True)),
                ('UG_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('PG_passing_year', models.IntegerField(blank=True, max_length=4, null=True)),
                ('PG_school', models.CharField(blank=True, max_length=50, null=True)),
                ('PG_board', models.CharField(blank=True, max_length=50, null=True)),
                ('PG_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_no', models.CharField(max_length=12, null=True, unique=True)),
                ('dob', models.DateField(null=True)),
                ('gender', models.CharField(max_length=1, null=True)),
                ('father_name', models.CharField(max_length=30, null=True)),
                ('mother_name', models.CharField(max_length=30, null=True)),
                ('aadhaar_no', models.CharField(max_length=12, null=True, unique=True)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
