# Generated by Django 2.2.6 on 2019-11-15 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_education',
            name='PG_passing_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student_education',
            name='UG_passing_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student_education',
            name='XII_passing_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student_education',
            name='X_passing_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
