# Generated by Django 2.2.6 on 2019-11-18 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_auto_20191115_2248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_detail',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='student_education',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AddField(
            model_name='student_detail',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
