# Generated by Django 2.2.6 on 2019-11-20 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_auto_20191118_1514'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_education',
            old_name='PG_board',
            new_name='PG_college',
        ),
        migrations.RenameField(
            model_name='student_education',
            old_name='PG_school',
            new_name='PG_university',
        ),
        migrations.RenameField(
            model_name='student_education',
            old_name='UG_board',
            new_name='UG_college',
        ),
        migrations.RemoveField(
            model_name='student_education',
            name='UG_school',
        ),
        migrations.AddField(
            model_name='student_education',
            name='UG_university',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
